# Generated by Django 6.0.6 on 2026-06-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Anonymous', max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('color_family', models.CharField(blank=True, default='Standard', max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('seller_response', models.TextField(blank=True, null=True)),
                ('seller_response_time', models.CharField(blank=True, default='12 months ago', max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
        ),
    ]
