# Generated by Django 6.0.6 on 2026-06-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='seller_response_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
