# Generated by Django 5.2.1 on 2026-06-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('IME', 'IME Pay')], default='COD', max_length=20),
        ),
    ]
