# Generated by Django 5.2.1 on 2026-06-28 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, default='No Brand', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_questions', models.IntegerField(default=0)),
                ('delivery_charge', models.IntegerField(default=105)),
                ('delivery_days', models.CharField(default='Guaranteed by 28 Jun', max_length=100)),
                ('cash_on_delivery', models.BooleanField(default=True)),
                ('change_of_mind', models.BooleanField(default=True)),
                ('return_days', models.IntegerField(default=14)),
                ('warranty_available', models.BooleanField(default=False)),
                ('warranty_info', models.CharField(blank=True, default='Warranty not available', max_length=200, null=True)),
                ('seller_name', models.CharField(default='EOrison', max_length=100)),
                ('positive_seller_ratings', models.IntegerField(default=84)),
                ('ship_on_time', models.IntegerField(default=100)),
                ('chat_response_rate', models.CharField(default='Not enough data', max_length=50)),
                ('item_form', models.CharField(blank=True, default='Solid', max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='wishlisted_by', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(help_text='e.g., Rs. 50 OFF or 10% OFF', max_length=50)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vouchers', to='products.product')),
            ],
        ),
    ]
