# Generated by Django 6.0.6 on 2026-06-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cash_on_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='change_of_mind',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.IntegerField(default=105),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.CharField(default='Guaranteed by 28 Jun', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='return_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.CharField(blank=True, default='Warranty not available', max_length=200, null=True),
        ),
    ]
