# Generated by Django 6.0.6 on 2026-06-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_cash_on_delivery_product_change_of_mind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chat_response_rate',
            field=models.CharField(default='Not enough data', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='positive_seller_ratings',
            field=models.IntegerField(default=84),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(default='EOrison', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ship_on_time',
            field=models.IntegerField(default=100),
        ),
    ]
