# Generated by Django 5.2.1 on 2026-07-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_stock_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=390, max_digits=10)),
                ('free_shipping_min_order', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
            ],
        ),
    ]
