# Generated by Django 6.0.6 on 2026-06-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_answered_questions_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, default='No Brand', max_length=100, null=True),
        ),
    ]
