# Generated by Django 6.0.6 on 2026-06-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_ratings',
        ),
    ]
