# Generated by Django 6.0.6 on 2026-06-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_rating_remove_product_total_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_form',
            field=models.CharField(blank=True, default='Solid', max_length=50, null=True),
        ),
    ]
